require('cfg.ro.utils.go-api')

Config.NewJob({
    JobType = JobType.Swordman,
    JobTier = JobTier.First,
    Base = JobType.Novice,
    Name = "Swordman",
    AspdBase = {
        [WeaponType.Fist] = 40,
        [WeaponType.Dagger] = 47,
        [WeaponType.Sword_1H] = 47,
        [WeaponType.Sword_2H] = 54,
        [WeaponType.Spear_1H] = 57,
        [WeaponType.Spear_2H] = 65,
        [WeaponType.Axe_1H] = 55,
        [WeaponType.Axe_2H] = 60,
        [WeaponType.Mace_1H] = 50,
        [WeaponType.Mace_2H] = 55,
    },
    MaxHPMod = 0.7,
    MaxSPMod = 2.0,
    CarryingCapacityMod = 800,
    BonusStats = {
        { Level = 2, Stat = Stat.Str },
        { Level = 6, Stat = Stat.Vit },
        { Level = 10, Stat = Stat.Dex },
        { Level = 14, Stat = Stat.Str },
        { Level = 18, Stat = Stat.Vit },
        { Level = 22, Stat = Stat.Dex },
        { Level = 26, Stat = Stat.Luk },
        { Level = 30, Stat = Stat.Agi },
        { Level = 33, Stat = Stat.Str },
        { Level = 36, Stat = Stat.Dex },
        { Level = 38, Stat = Stat.Vit },
        { Level = 40, Stat = Stat.Str },
        { Level = 42, Stat = Stat.Vit },
        { Level = 44, Stat = Stat.Luk },
        { Level = 46, Stat = Stat.Agi },
        { Level = 47, Stat = Stat.Str },
        { Level = 49, Stat = Stat.Str },
        { Level = 50, Stat = Stat.Str },
    }
})
Config.NewJob({
    JobType = JobType.Mage,
    JobTier = JobTier.First,
    Base = JobType.Novice,
    Name = "Mage",
    AspdBase = {
        [WeaponType.Fist] = 50,
        [WeaponType.Dagger] = 50,
        [WeaponType.Staff_1H] = 55,
        [WeaponType.Staff_2H] = 55,
    },
    MaxHPMod = 0.3,
    MaxSPMod = 6.0,
    CarryingCapacityMod = 200,
    BonusStats = {
        { Level = 2, Stat = Stat.Int },
        { Level = 6, Stat = Stat.Dex },
        { Level = 10, Stat = Stat.Dex },
        { Level = 14, Stat = Stat.Int },
        { Level = 18, Stat = Stat.Agi },
        { Level = 22, Stat = Stat.Int },
        { Level = 26, Stat = Stat.Agi },
        { Level = 30, Stat = Stat.Luk },
        { Level = 33, Stat = Stat.Int },
        { Level = 36, Stat = Stat.Dex },
        { Level = 38, Stat = Stat.Int },
        { Level = 40, Stat = Stat.Agi },
        { Level = 42, Stat = Stat.Luk },
        { Level = 44, Stat = Stat.Int },
        { Level = 46, Stat = Stat.Int },
        { Level = 47, Stat = Stat.Agi },
        { Level = 49, Stat = Stat.Luk },
        { Level = 50, Stat = Stat.Int },
    }
})
Config.NewJob({
    JobType = JobType.Archer,
    JobTier = JobTier.First,
    Base = JobType.Novice,
    Name = "Archer",
    AspdBase = {
        [WeaponType.Fist] = 40,
        [WeaponType.Dagger] = 55,
        [WeaponType.Bow] = 50
    },
    MaxHPMod = 0.5,
    MaxSPMod = 2.0,
    CarryingCapacityMod = 600,
    BonusStats = {
        { Level = 2, Stat = Stat.Dex },
        { Level = 6, Stat = Stat.Str },
        { Level = 10, Stat = Stat.Int },
        { Level = 14, Stat = Stat.Dex },
        { Level = 18, Stat = Stat.Dex },
        { Level = 22, Stat = Stat.Luk },
        { Level = 26, Stat = Stat.Agi },
        { Level = 30, Stat = Stat.Dex },
        { Level = 33, Stat = Stat.Agi },
        { Level = 36, Stat = Stat.Dex },
        { Level = 38, Stat = Stat.Str },
        { Level = 40, Stat = Stat.Str },
        { Level = 42, Stat = Stat.Dex },
        { Level = 44, Stat = Stat.Luk },
        { Level = 46, Stat = Stat.Vit },
        { Level = 47, Stat = Stat.Int },
        { Level = 49, Stat = Stat.Agi },
        { Level = 50, Stat = Stat.Dex },
    }
})
Config.NewJob({
    JobType = JobType.Acolyte,
    JobTier = JobTier.First,
    Base = JobType.Novice,
    Name = "Acolyte",
    AspdBase = {
        [WeaponType.Fist] = 40,
        [WeaponType.Mace_1H] = 45,
        [WeaponType.Mace_2H] = 50,
        [WeaponType.Staff_1H] = 60,
        [WeaponType.Staff_2H] = 60
    },
    MaxHPMod = 0.4,
    MaxSPMod = 5.0,
    CarryingCapacityMod = 400,
    BonusStats = {
        { Level = 2, Stat = Stat.Luk },
        { Level = 6, Stat = Stat.Vit },
        { Level = 10, Stat = Stat.Int },
        { Level = 14, Stat = Stat.Dex },
        { Level = 18, Stat = Stat.Luk },
        { Level = 22, Stat = Stat.Agi },
        { Level = 26, Stat = Stat.Str },
        { Level = 30, Stat = Stat.Vit },
        { Level = 33, Stat = Stat.Int },
        { Level = 36, Stat = Stat.Dex },
        { Level = 38, Stat = Stat.Luk },
        { Level = 40, Stat = Stat.Agi },
        { Level = 42, Stat = Stat.Str },
        { Level = 44, Stat = Stat.Vit },
        { Level = 46, Stat = Stat.Int },
        { Level = 47, Stat = Stat.Dex },
        { Level = 49, Stat = Stat.Str },
        { Level = 50, Stat = Stat.Luk },
    }
})
Config.NewJob({
    JobType = JobType.Merchant,
    JobTier = JobTier.First,
    Base = JobType.Novice,
    Name = "Merchant",
    AspdBase = {
        [WeaponType.Fist] = 40,
        [WeaponType.Dagger] = 52,
        [WeaponType.Sword_1H] = 52,
        [WeaponType.Axe_1H] = 48,
        [WeaponType.Axe_2H] = 55,
        [WeaponType.Mace_1H] = 50,
        [WeaponType.Mace_2H] = 55,
    },
    MaxHPMod = 0.4,
    MaxSPMod = 3.0,
    CarryingCapacityMod = 800,
    BonusStats = {
        { Level = 2, Stat = Stat.Vit },
        { Level = 6, Stat = Stat.Dex },
        { Level = 10, Stat = Stat.Str },
        { Level = 14, Stat = Stat.Dex },
        { Level = 18, Stat = Stat.Vit },
        { Level = 22, Stat = Stat.Str },
        { Level = 26, Stat = Stat.Int },
        { Level = 30, Stat = Stat.Vit },
        { Level = 33, Stat = Stat.Agi },
        { Level = 36, Stat = Stat.Luk },
        { Level = 38, Stat = Stat.Dex },
        { Level = 40, Stat = Stat.Str },
        { Level = 42, Stat = Stat.Dex },
        { Level = 44, Stat = Stat.Str },
        { Level = 46, Stat = Stat.Luk },
        { Level = 47, Stat = Stat.Vit },
        { Level = 49, Stat = Stat.Str },
        { Level = 50, Stat = Stat.Dex },
    }
})
Config.NewJob({
    JobType = JobType.Thief,
    JobTier = JobTier.First,
    Base = JobType.Novice,
    Name = "Thief",
    AspdBase = {
        [WeaponType.Fist] = 40,
        [WeaponType.Dagger] = 48,
        [WeaponType.Sword_1H] = 50,
        [WeaponType.Axe_1H] = 60,
        [WeaponType.Bow] = 53,
    },
    MaxHPMod = 0.5,
    MaxSPMod = 2.0,
    CarryingCapacityMod = 400,
    BonusStats = {
        { Level = 2, Stat = Stat.Agi },
        { Level = 6, Stat = Stat.Str },
        { Level = 10, Stat = Stat.Dex },
        { Level = 14, Stat = Stat.Vit },
        { Level = 18, Stat = Stat.Int },
        { Level = 22, Stat = Stat.Dex },
        { Level = 26, Stat = Stat.Luk },
        { Level = 30, Stat = Stat.Str },
        { Level = 33, Stat = Stat.Agi },
        { Level = 36, Stat = Stat.Agi },
        { Level = 38, Stat = Stat.Str },
        { Level = 40, Stat = Stat.Luk },
        { Level = 42, Stat = Stat.Dex },
        { Level = 44, Stat = Stat.Vit },
        { Level = 46, Stat = Stat.Luk },
        { Level = 47, Stat = Stat.Str },
        { Level = 49, Stat = Stat.Dex },
        { Level = 50, Stat = Stat.Agi },
    }
})
