require('cfg.ro.utils.go-api')

Config.NewJob({
    JobType = JobType.Knight,
    JobTier = JobTier.Second,
    Base = JobType.Swordman,
    Name = "Knight",
    Skills = {
        "bowling_bash",
        "brandish_spear",
        "cavalier_mastery",
        "counter_attack",
        "peco_peco_ride",
        "pierce",
        "spear_boomerang",
        "spear_mastery",
        "spear_stab",
        "twohand_quicken",
        "charge_attack",
    },
    AspdBase = {
        [WeaponType.Fist] = 40,
        [WeaponType.Dagger] = 49,
        [WeaponType.Sword_1H] = 45,
        [WeaponType.Sword_2H] = 52,
        [WeaponType.Spear_1H] = 55,
        [WeaponType.Spear_2H] = 60,
        [WeaponType.Axe_1H] = 50,
        [WeaponType.Axe_2H] = 55,
        [WeaponType.Mace_1H] = 45,
        [WeaponType.Mace_2H] = 50,
    },
    MaxHPMod = 1.5,
    MaxSPMod = 3.0,
    CarryingCapacityMod = 800,
    BonusStats = {
        { Level = 1, Stat = Stat.Vit },
        { Level = 3, Stat = Stat.Vit },
        { Level = 4, Stat = Stat.Str },
        { Level = 5, Stat = Stat.Luk },
        { Level = 8, Stat = Stat.Vit },
        { Level = 10, Stat = Stat.Str },
        { Level = 11, Stat = Stat.Dex },
        { Level = 12, Stat = Stat.Vit },
        { Level = 13, Stat = Stat.Agi },
        { Level = 15, Stat = Stat.Str },
        { Level = 17, Stat = Stat.Vit },
        { Level = 18, Stat = Stat.Vit },
        { Level = 19, Stat = Stat.Dex },
        { Level = 20, Stat = Stat.Luk },
        { Level = 21, Stat = Stat.Str },
        { Level = 23, Stat = Stat.Vit },
        { Level = 27, Stat = Stat.Str },
        { Level = 28, Stat = Stat.Luk },
        { Level = 29, Stat = Stat.Vit },
        { Level = 31, Stat = Stat.Dex },
        { Level = 33, Stat = Stat.Str },
        { Level = 36, Stat = Stat.Vit },
        { Level = 37, Stat = Stat.Luk },
        { Level = 38, Stat = Stat.Agi },
        { Level = 40, Stat = Stat.Dex },
        { Level = 43, Stat = Stat.Vit },
        { Level = 46, Stat = Stat.Str },
        { Level = 47, Stat = Stat.Str },
        { Level = 48, Stat = Stat.Dex },
        { Level = 49, Stat = Stat.Dex },
    }
})
Config.NewJob({
    JobType = JobType.Priest,
    JobTier = JobTier.Second,
    Base = JobType.Acolyte,
    Name = "Priest",
    Skills = {
        "aspersio",
        "b.s_sacramenti",
        "gloria",
        "impositio_manus",
        "increase_sp_recovery",
        "kyrie_eleison",
        "lex_aeterna",
        "lex_divina",
        "mace_mastery",
        "magnificat",
        "magnus_exorcismus",
        "resurrection",
        "safety_wall",
        "sanctuary",
        "slow_poison",
        "status_recovery",
        "suffragium",
        "turn_undead",
        "redemptio",
    },
    AspdBase = {
        [WeaponType.Fist] = 40,
        [WeaponType.Mace_1H] = 43,
        [WeaponType.Mace_2H] = 48,
        [WeaponType.Staff_1H] = 60,
        [WeaponType.Knuckle] = 60,
        [WeaponType.Book] = 44,
        [WeaponType.Staff_2H] = 60,
    },
    MaxHPMod = 0.75,
    MaxSPMod = 8.0,
    CarryingCapacityMod = 600,
    BonusStats = {
        { Level = 1, Stat = Stat.Luk },
        { Level = 3, Stat = Stat.Luk },
        { Level = 4, Stat = Stat.Str },
        { Level = 6, Stat = Stat.Agi },
        { Level = 7, Stat = Stat.Vit },
        { Level = 8, Stat = Stat.Int },
        { Level = 9, Stat = Stat.Int },
        { Level = 10, Stat = Stat.Luk },
        { Level = 11, Stat = Stat.Str },
        { Level = 14, Stat = Stat.Vit },
        { Level = 16, Stat = Stat.Dex },
        { Level = 17, Stat = Stat.Str },
        { Level = 20, Stat = Stat.Dex },
        { Level = 21, Stat = Stat.Luk },
        { Level = 22, Stat = Stat.Int },
        { Level = 25, Stat = Stat.Dex },
        { Level = 27, Stat = Stat.Str },
        { Level = 29, Stat = Stat.Agi },
        { Level = 31, Stat = Stat.Luk },
        { Level = 32, Stat = Stat.Dex },
        { Level = 34, Stat = Stat.Vit },
        { Level = 35, Stat = Stat.Str },
        { Level = 36, Stat = Stat.Vit },
        { Level = 37, Stat = Stat.Agi },
        { Level = 39, Stat = Stat.Luk },
        { Level = 42, Stat = Stat.Int },
        { Level = 43, Stat = Stat.Int },
        { Level = 45, Stat = Stat.Vit },
        { Level = 48, Stat = Stat.Agi },
        { Level = 50, Stat = Stat.Luk },
    }
})
